name: Trigger Vercel Rebuild

on:
  schedule:
    - cron: '0 */1 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Rebuild
        run:
          curl -X POST
          'https://api.vercel.com/v1/integrations/deploy/prj_ldAQugKuNWYNbnxl7r3sBrvkGgNU/RyqPqim7eR'
